build_from:
  amd64: "https://hub.docker.com/r/amd64/wordpress/"
  armv7: "https://hub.docker.com/r/arm32v7/wordpress/"
  aarch64: "https://hub.docker.com/r/arm64v8/wordpress/"
  i386: "https://hub.docker.com/r/i386/wordpress/"
codenotary:
  signer: "github.com@wanno.eu"
args:
