build_from:
  amd64: "https://hub.docker.com/r/amd64/wordpress/"
  arm32v5: "https://hub.docker.com/r/arm32v5/wordpress/"
  arm32v6: "https://hub.docker.com/r/arm32v6/wordpress/"
  arm32v7: "https://hub.docker.com/r/arm32v7/wordpress/"
  arm64v8: "https://hub.docker.com/r/arm64v8/wordpress/"
  i386: "https://hub.docker.com/r/i386/wordpress/"
  mips64le: "https://hub.docker.com/r/mips64le/wordpress/"
  ppc64le: "https://hub.docker.com/r/ppc64le/wordpress/"
  s390x: "https://hub.docker.com/r/s390x/wordpress/"
codenotary:
  signer: "github.com@wanno.eu"
args:
