name: "Wordpress"
description: "WordPress is a free and open source blogging tool and a content management system."
version: "1.0.0"
slug: "wordpress"
init: false
arch:
  - amd64
  - armv5
  - armv6
  - armv7
  - armv8
  - i386
  - mips64le
  - ppc64le
  - s390x