name: WordPress
description: "WordPress is a free and open source blogging tool and a content management system."
version: "1.0.18"
slug: wordpress
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
url: https://github.com/wanno-drijfhout/home-assistant-goodies/blob/master/wordpress/Readme.md
startup: application
webui: http://[HOST]:[PORT:8090]/wp-admin
# ports:
#   80/tcp: 8099
# ports_description:
#   80/tcp: "HTTP"
ingress: true
ingress_stream: true
ingress_port: 80
map:
  - share:rw
  - media:rw
environment:
  WORDPRESS_DB_HOST: core-mariadb:3306
  WORDPRESS_DB_NAME: wordpress
  WORDPRESS_DB_USER: wordpress
  WORDPRESS_DB_PASSWORD: ""
services:
  - mysql:need
panel_icon: mdi:wordpress
stage: experimental
options:
  db_name: wordpress
  db_username: wordpress
  db_password: null
schema:
  db_name: str
  db_username: str
  db_password: password
#codenotary: github.com@wanno.eu
hassio_role: default